services:
  app:
    build: .
    container_name: file_server_app
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/file_server
      - JWT_SECRET=your_jwt_secret
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - ./app:/app


  mongo:
    image: mongo
    container_name: file_server_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./init-db:/docker-entrypoint-initdb.d


volumes:
  mongo-data:
