services:
  app:
    build: .
    container_name: file_server_app
    environment:
      - PORT=3000
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=my_password
      - DB_NAME=file_server
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    volumes:
      - ./app:/app

  mysql:
    image: mysql:5.7
    container_name: file_server_mysql
    environment:
      MYSQL_ROOT_PASSWORD: my_password
      MYSQL_DATABASE: file_server
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./app/src/init-db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data:
